"""
QA Escalation to Human
=======================

Handles escalation of QA blockers to human intervention.
Creates clear, actionable requests and pauses QA until resolved.

Escalation types:
- NEED_CREDENTIALS: Login credentials required for E2E testing
- NEED_DEV_SERVER: Dev server configuration required
- RECURRING_ISSUE: Same issue appearing 3+ times
- MAX_ITERATIONS: Reached maximum QA iterations
- CUSTOM_BLOCKER: Project-specific blocker needing human decision
"""

from datetime import datetime, timezone
from pathlib import Path

from debug import debug, debug_section, debug_success
from phase_event import ExecutionPhase, emit_phase

from .config import (
    DevServerConfig,
    QAConfig,
    create_default_qa_config,
    guess_dev_server_config,
    load_qa_config,
    save_qa_config,
)


# =============================================================================
# ESCALATION FILE CREATION
# =============================================================================


def create_escalation_file(
    spec_dir: Path,
    escalation_type: str,
    title: str,
    description: str,
    required_inputs: list[dict],
    example_config: str,
    additional_context: str | None = None
) -> Path:
    """
    Create a human-readable escalation request file.

    Args:
        spec_dir: Spec directory
        escalation_type: Type of escalation (for tracking)
        title: Human-readable title
        description: What's needed and why
        required_inputs: List of {name, description, example} dicts
        example_config: Example qa_config.json snippet
        additional_context: Optional extra information

    Returns:
        Path to created escalation file
    """
    escalation_file = spec_dir / "QA_HUMAN_INPUT_NEEDED.md"

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    content = f"""# QA Needs Human Input

**Type:** {escalation_type}
**Created:** {timestamp}
**Spec:** {spec_dir.name}

---

## {title}

{description}

---

## Required Information

"""

    for inp in required_inputs:
        content += f"### {inp['name']}\n"
        content += f"{inp['description']}\n"
        if inp.get('example'):
            content += f"\n**Example:** `{inp['example']}`\n"
        content += "\n"

    content += f"""---

## How to Provide

Edit `{spec_dir.name}/qa_config.json`:

```json
{example_config}
```

**Then re-run QA:**
```bash
python run.py --spec {spec_dir.name.split('-')[0]} --qa
```

"""

    if additional_context:
        content += f"""---

## Additional Context

{additional_context}

"""

    content += f"""---

_This file was auto-generated by Ouro QA._
_It will be removed once you provide the required input and re-run QA._
"""

    escalation_file.write_text(content)

    debug_success("qa_escalation", f"Created escalation file: {escalation_file}")

    return escalation_file


# =============================================================================
# SPECIFIC ESCALATION TYPES
# =============================================================================


async def escalate_for_credentials(
    spec_dir: Path,
    project_dir: Path,
    detected_login_url: str | None = None
) -> Path:
    """
    Escalate to human for login credentials.

    Creates clear request explaining what's needed for E2E testing.
    """
    debug_section("qa_escalation", "Escalating for credentials")

    # Emit event for frontend
    emit_phase(ExecutionPhase.HUMAN_INPUT_NEEDED, "Login credentials required for E2E testing")

    additional_context = None
    if detected_login_url:
        additional_context = f"Detected login page at: `{detected_login_url}`"

    example_config = """{
  "credentials": {
    "default": {
      "username": "YOUR_TEST_USERNAME",
      "password": "YOUR_TEST_PASSWORD"
    }
  }
}"""

    escalation_file = create_escalation_file(
        spec_dir=spec_dir,
        escalation_type="NEED_CREDENTIALS",
        title="Login Credentials Required",
        description="""The E2E tests need to authenticate to test the application.
Without valid credentials, tests that require login will fail.

**Why this is needed:**
- Playwright needs to fill in login form
- Tests behind authentication cannot proceed
- This is a one-time setup - credentials will be reused for all future QA iterations""",
        required_inputs=[
            {
                "name": "Username / Email",
                "description": "The test account username or email address",
                "example": "test@example.com"
            },
            {
                "name": "Password",
                "description": "The test account password",
                "example": "testpassword123"
            }
        ],
        example_config=example_config,
        additional_context=additional_context
    )

    # Print to console for visibility
    print("\n" + "=" * 70)
    print("  HUMAN INPUT NEEDED: Login Credentials")
    print("=" * 70)
    print("\nQA E2E tests require login credentials to proceed.")
    print(f"\nSee: {escalation_file}")
    print("\nProvide credentials in qa_config.json and re-run --qa")
    print("=" * 70 + "\n")

    return escalation_file


async def escalate_for_dev_server(
    spec_dir: Path,
    project_dir: Path
) -> Path:
    """
    Escalate to human for dev server configuration.

    Includes auto-detected suggestions if available.
    """
    debug_section("qa_escalation", "Escalating for dev server config")

    # Emit event for frontend
    emit_phase(ExecutionPhase.HUMAN_INPUT_NEEDED, "Dev server configuration required")

    # Try to provide helpful suggestions
    guessed_config = guess_dev_server_config(project_dir)

    additional_context = None
    if guessed_config:
        additional_context = f"""**Auto-detected suggestion:**
- Start command: `{guessed_config.get('start_command', 'unknown')}`
- Base URL: `{guessed_config.get('base_url', 'unknown')}`

Please verify these are correct for your project."""

    example_config = """{
  "dev_server": {
    "start_command": "npm run dev",
    "base_url": "http://localhost:3000",
    "health_check_url": "http://localhost:3000/api/health",
    "startup_timeout_seconds": 30
  }
}"""

    escalation_file = create_escalation_file(
        spec_dir=spec_dir,
        escalation_type="NEED_DEV_SERVER",
        title="Dev Server Configuration Required",
        description="""The E2E tests need to know how to start and access the development server.
Without this, Playwright cannot navigate to your application.

**Why this is needed:**
- QA needs to start the dev server before running E2E tests
- Playwright needs the base URL to navigate to pages
- Health check ensures server is ready before tests begin""",
        required_inputs=[
            {
                "name": "Start Command",
                "description": "Command to start the development server",
                "example": "npm run dev"
            },
            {
                "name": "Base URL",
                "description": "URL where the dev server will be accessible",
                "example": "http://localhost:3000"
            },
            {
                "name": "Health Check URL (optional)",
                "description": "URL to check if server is ready (defaults to base URL)",
                "example": "http://localhost:3000/api/health"
            }
        ],
        example_config=example_config,
        additional_context=additional_context
    )

    # Print to console for visibility
    print("\n" + "=" * 70)
    print("  HUMAN INPUT NEEDED: Dev Server Configuration")
    print("=" * 70)
    print("\nQA E2E tests need to know how to start your dev server.")

    if guessed_config:
        print(f"\nAuto-detected suggestion:")
        print(f"  Start: {guessed_config.get('start_command', '?')}")
        print(f"  URL:   {guessed_config.get('base_url', '?')}")
        print("\nPlease verify and add to qa_config.json")
    else:
        print("\nCould not auto-detect - please configure manually.")

    print(f"\nSee: {escalation_file}")
    print("=" * 70 + "\n")

    return escalation_file


async def escalate_recurring_issues(
    spec_dir: Path,
    recurring_issues: list[dict],
    iteration_count: int
) -> Path:
    """
    Escalate to human when same issues keep recurring.

    This indicates the automated fixes aren't working and human
    judgment is needed.
    """
    debug_section("qa_escalation", "Escalating recurring issues")

    emit_phase(ExecutionPhase.HUMAN_INPUT_NEEDED,
               f"{len(recurring_issues)} recurring issues need human review")

    # Format issue list
    issues_text = ""
    for i, issue in enumerate(recurring_issues, 1):
        issues_text += f"""
### Issue {i}: {issue.get('title', 'Unknown')}

**Occurrences:** {issue.get('recurrence_count', '?')} times
**First seen:** Iteration {issue.get('found_in', '?')}
**Location:** `{issue.get('location', 'Unknown')}`

**Previous fix attempts:**
"""
        for attempt in issue.get('fix_attempts', []):
            issues_text += f"- {attempt.get('iteration', '?')}: {attempt.get('fix_description', 'Unknown')} → {attempt.get('outcome', 'Unknown')}\n"
            if attempt.get('reason'):
                issues_text += f"  Reason: {attempt.get('reason')}\n"

    content = f"""# QA Needs Human Review

**Type:** RECURRING_ISSUES
**Created:** {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")}
**Spec:** {spec_dir.name}
**Iterations completed:** {iteration_count}

---

## Recurring Issues Detected

The following issues have appeared **3 or more times** despite fix attempts.
Automated fixes are not resolving them - human judgment is needed.

{issues_text}

---

## What You Can Do

1. **Review the issues above** - understand what's failing and why fixes aren't working

2. **Option A: Fix manually**
   - Make the fix yourself in the codebase
   - Run `python run.py --spec {spec_dir.name.split('-')[0]} --qa` to re-validate

3. **Option B: Mark as acceptable**
   - If this is expected behavior, add to `qa_config.json`:
   ```json
   {{
     "human_approvals": {{
       "known_acceptable_issues": ["{recurring_issues[0].get('title', 'issue_name')}"]
     }}
   }}
   ```

4. **Option C: Skip specific tests**
   - If tests are flaky, add to `qa_config.json`:
   ```json
   {{
     "human_approvals": {{
       "skip_flaky_tests": ["test_name_here"]
     }}
   }}
   ```

---

## Files for Context

- `qa_report.md` - Latest QA report with full details
- `QA_FIX_REQUEST.md` - Last fix request sent to fixer
- `implementation_plan.json` - Full iteration history

---

_QA loop has been paused. Will resume when you re-run --qa._
"""

    escalation_file = spec_dir / "QA_HUMAN_REVIEW_NEEDED.md"
    escalation_file.write_text(content)

    print("\n" + "=" * 70)
    print("  RECURRING ISSUES - Human Review Needed")
    print("=" * 70)
    print(f"\n{len(recurring_issues)} issue(s) have appeared 3+ times despite fixes.")
    print("\nAutomated QA cannot resolve these. Please review:")
    for issue in recurring_issues[:3]:
        print(f"  - {issue.get('title', 'Unknown')}")
    print(f"\nSee: {escalation_file}")
    print("=" * 70 + "\n")

    return escalation_file


# =============================================================================
# ESCALATION STATUS
# =============================================================================


def has_pending_escalation(spec_dir: Path) -> tuple[bool, str | None]:
    """
    Check if there's a pending escalation that needs human input.

    Returns:
        (has_pending, escalation_type) tuple
    """
    # Check for escalation files
    escalation_files = [
        ("QA_HUMAN_INPUT_NEEDED.md", "input_needed"),
        ("QA_HUMAN_REVIEW_NEEDED.md", "review_needed"),
    ]

    for filename, esc_type in escalation_files:
        if (spec_dir / filename).exists():
            debug("qa_escalation", f"Found pending escalation: {filename}")
            return True, esc_type

    return False, None


def clear_escalation(spec_dir: Path) -> bool:
    """
    Clear escalation files after human has provided input.

    Called when QA prerequisites are now met.
    """
    escalation_files = [
        "QA_HUMAN_INPUT_NEEDED.md",
        "QA_HUMAN_REVIEW_NEEDED.md",
    ]

    cleared = False
    for filename in escalation_files:
        filepath = spec_dir / filename
        if filepath.exists():
            filepath.unlink()
            debug_success("qa_escalation", f"Cleared escalation: {filename}")
            cleared = True

    return cleared


# =============================================================================
# APPLY AUTO-DETECTED CONFIG
# =============================================================================


async def apply_auto_detected_config(spec_dir: Path, project_dir: Path) -> bool:
    """
    Apply auto-detected configuration (dev server) if user hasn't configured.

    This provides sensible defaults that can be overridden.
    Returns True if any config was auto-applied.
    """
    config = load_qa_config(spec_dir) or create_default_qa_config(spec_dir, spec_dir.name)
    applied = False

    # Auto-apply dev server config if not set
    if not config.get("dev_server") or not config["dev_server"].get("start_command"):
        guessed = guess_dev_server_config(project_dir)
        if guessed:
            config["dev_server"] = DevServerConfig(
                start_command=guessed.get("start_command", ""),
                base_url=guessed.get("base_url", ""),
                health_check_url=guessed.get("base_url", ""),
                startup_timeout_seconds=30,
                provided_by_human=False,  # Mark as auto-detected
                provided_at=datetime.now(timezone.utc).isoformat(),
            )
            applied = True
            debug("qa_escalation", "Auto-applied dev server config",
                  command=guessed.get("start_command"),
                  url=guessed.get("base_url"))

    if applied:
        save_qa_config(spec_dir, config)

    return applied
